export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_EDUCATION = 'UPDATE_EDUCATION';
export const UPDATE_WORK = 'UPDATE_WORK';
export const UPDATE_SKILL_AND_LANG = 'UPDATE_SKILL_AND_LANG';
export const UPDATE_PROJECT = 'UPDATE_PROJECT'